
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SysAid
{

using System;
    using System.Collections.Generic;
    
public partial class Integridad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Integridad()
    {

        this.ListadoActivos = new HashSet<ListadoActivos>();

    }


    public int idIntegridad { get; set; }

    public byte nivelIntegridad { get; set; }

    public string nivel { get; set; }

    public string descripcion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ListadoActivos> ListadoActivos { get; set; }

}

}
