
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SysAid
{

using System;
    using System.Collections.Generic;
    
public partial class ListadoRiesgo
{

    public int idListadoRiesgo { get; set; }

    public string codigoActivo { get; set; }

    public Nullable<int> idVulnerabilidad { get; set; }

    public Nullable<int> idAmenaza { get; set; }

    public Nullable<int> idControl { get; set; }

    public Nullable<double> riesgo { get; set; }



    public virtual Amenaza Amenaza { get; set; }

    public virtual Controles Controles { get; set; }

    public virtual ListadoActivos ListadoActivos { get; set; }

    public virtual Vulnerabilidad Vulnerabilidad { get; set; }

}

}
