

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SysAid
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ValoracionActivosEntities : DbContext
{
    public ValoracionActivosEntities()
        : base("name=ValoracionActivosEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Amenaza> Amenaza { get; set; }

    public virtual DbSet<AreaActivo> AreaActivo { get; set; }

    public virtual DbSet<Confidencialidad> Confidencialidad { get; set; }

    public virtual DbSet<Controles> Controles { get; set; }

    public virtual DbSet<Disponibilidad> Disponibilidad { get; set; }

    public virtual DbSet<Integridad> Integridad { get; set; }

    public virtual DbSet<ListadoActivos> ListadoActivos { get; set; }

    public virtual DbSet<ListadoRiesgo> ListadoRiesgo { get; set; }

    public virtual DbSet<TipoActivo> TipoActivo { get; set; }

    public virtual DbSet<Vulnerabilidad> Vulnerabilidad { get; set; }

}

}

