
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SysAid
{

using System;
    using System.Collections.Generic;
    
public partial class TipoActivo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoActivo()
    {

        this.ListadoActivos = new HashSet<ListadoActivos>();

        this.Vulnerabilidad = new HashSet<Vulnerabilidad>();

    }


    public int idTipoActivo { get; set; }

    public string tipo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ListadoActivos> ListadoActivos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vulnerabilidad> Vulnerabilidad { get; set; }

}

}
