
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SysAid
{

using System;
    using System.Collections.Generic;
    
public partial class Vulnerabilidad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vulnerabilidad()
    {

        this.ListadoRiesgo = new HashSet<ListadoRiesgo>();

    }


    public int idVulnerabilidad { get; set; }

    public Nullable<int> tipoActivo { get; set; }

    public string nombre { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ListadoRiesgo> ListadoRiesgo { get; set; }

    public virtual TipoActivo TipoActivo1 { get; set; }

}

}
